/**
 * Remotion component-template library for Motion-Pro generation.
 * COMP_DEFS holds the literal TSX source for each advanced component
 * (GlowCard, AnimatedText, OdometerDigit, etc — base components C/Safe/E/Fd
 * are always included elsewhere). TYPE_COMPONENTS maps each motion type to
 * the advanced components it needs; getComponentsForType() resolves
 * dependencies and returns the joined TSX source to inline into the prompt.
 */

// ──────────────────────────────────────────────────────────────────────────────
// Component definitions for the code template
// Base components (C, Safe, E, Fd) are ALWAYS included.
// These advanced components are selected per animation type.
// NOTE: These strings contain TSX code with template literals — backticks
// and ${} are literal characters (not JS interpolation).
// ──────────────────────────────────────────────────────────────────────────────

const COMP_DEFS = {
  AnimatedText: [
    'const AnimatedText:React.FC<{',
    '  text:string;',
    '  d:number;',
    '  fontSize?:number;',
    '  fontWeight?:number;',
    '  color?:string;',
    "  align?:'left'|'center'|'right';",
    "  mode?:'word'|'line'|'fade';",
    '  framesPerWord?:number;',
    "}> = ({text, d, fontSize=36, fontWeight=700, color=C.text, align='center', mode='word', framesPerWord=4}) => {",
    '  const frame = useCurrentFrame();',
    "  const words = text.split(' ');",
    '  ',
    "  if (mode === 'fade') {",
    '    const progress = interpolate(frame - d, [0, 25], [0, 1], {',
    '      easing: Easing.bezier(0.16, 1, 0.3, 1),',
    "      extrapolateLeft: 'clamp', extrapolateRight: 'clamp',",
    '    });',
    '    return (',
    '      <div style={{fontSize, fontWeight, color, textAlign:align, opacity:progress, ',
    '        transform:`translateY(${interpolate(progress,[0,1],[30,0])}px)`}}>',
    '        {text}',
    '      </div>',
    '    );',
    '  }',
    '  ',
    '  return (',
    "    <div style={{fontSize, fontWeight, textAlign:align, display:'flex', flexWrap:'wrap', ",
    "      justifyContent: align === 'center' ? 'center' : align === 'right' ? 'flex-end' : 'flex-start',",
    '      gap: `0 ${fontSize * 0.3}px`}}>',
    '      {words.map((word, i) => {',
    '        const wordDelay = d + i * framesPerWord;',
    '        const progress = interpolate(frame - wordDelay, [0, 12], [0, 1], {',
    '          easing: Easing.bezier(0.16, 1, 0.3, 1),',
    "          extrapolateLeft: 'clamp', extrapolateRight: 'clamp',",
    '        });',
    '        return (',
    '          <span key={i} style={{',
    '            color,',
    '            opacity: progress,',
    '            transform: `translateY(${interpolate(progress, [0,1], [20, 0])}px)`,',
    "            display: 'inline-block',",
    '          }}>',
    '            {word}',
    '          </span>',
    '        );',
    '      })}',
    '    </div>',
    '  );',
    '};',
  ].join('\n'),

  GlowCard: [
    'const GlowCard:React.FC<{',
    '  children:React.ReactNode;',
    '  d:number;',
    '  from?:string;',
    '  accent?:string;',
    '  elevation?:1|2|3|4;',
    "  width?:number|string;",
    '  active?:boolean;',
    '  style?:React.CSSProperties;',
    "}> = ({children, d, from='up', accent=C.accent, elevation=2, width='auto', active=true, style}) => {",
    '  const frame = useCurrentFrame();',
    '  ',
    '  const shadows:{[key:number]:string} = {',
    "    1: '0 2px 8px rgba(0,0,0,0.3)',",
    "    2: '0 8px 32px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.06)',",
    "    3: '0 16px 48px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.08)',",
    '    4: `0 8px 32px ${accent}20, 0 0 60px ${accent}08, 0 0 0 1px ${accent}30`,',
    '  };',
    '',
    '  const glowIntensity = active ',
    "    ? interpolate(frame % 120, [0, 60, 120], [0.03, 0.06, 0.03], {extrapolateRight:'clamp', extrapolateLeft:'clamp'})",
    '    : 0;',
    '  ',
    '  return (',
    '    <E d={d} from={from} style={{width, ...style}}>',
    '      <div style={{',
    '        backgroundColor: C.card,',
    '        borderRadius: 16,',
    '        padding: 32,',
    '        border: active ? `1px solid ${accent}30` : `1px solid ${C.border}`,',
    '        boxShadow: shadows[active ? Math.max(elevation, 3) : elevation],',
    "        position: 'relative',",
    "        overflow: 'hidden',",
    '      }}>',
    '        {active && (',
    '          <div style={{',
    "            position: 'absolute', top: 0, left: 0, right: 0, height: 2,",
    '            background: `linear-gradient(90deg, transparent, ${accent}, transparent)`,',
    '            opacity: 0.6,',
    '          }}/>',
    '        )}',
    '        {active && (',
    '          <div style={{',
    "            position: 'absolute', top: -50, right: -50, width: 200, height: 200,",
    "            background: `radial-gradient(circle, ${accent}${Math.round(glowIntensity * 255).toString(16).padStart(2,'0')}, transparent 70%)`,",
    "            pointerEvents: 'none',",
    '          }}/>',
    '        )}',
    "        <div style={{position:'relative', zIndex:1}}>",
    '          {children}',
    '        </div>',
    '      </div>',
    '    </E>',
    '  );',
    '};',
  ].join('\n'),

  AnimatedLine: [
    'const AnimatedLine:React.FC<{',
    '  x1:number; y1:number; x2:number; y2:number;',
    '  d:number;',
    '  color?:string;',
    '  strokeWidth?:number;',
    '  dashed?:boolean;',
    '  duration?:number;',
    '}> = ({x1, y1, x2, y2, d, color=C.accent, strokeWidth=2, dashed=false, duration=30}) => {',
    '  const frame = useCurrentFrame();',
    '  const progress = interpolate(frame - d, [0, duration], [0, 1], {',
    '    easing: Easing.bezier(0.16, 1, 0.3, 1),',
    "    extrapolateLeft: 'clamp', extrapolateRight: 'clamp',",
    '  });',
    '  ',
    '  const length = Math.sqrt(Math.pow(x2-x1, 2) + Math.pow(y2-y1, 2));',
    '  ',
    '  return (',
    "    <svg style={{position:'absolute', top:0, left:0, width:'100%', height:'100%', pointerEvents:'none', zIndex:0}}>",
    '      <line',
    '        x1={x1} y1={y1} x2={x2} y2={y2}',
    '        stroke={color}',
    '        strokeWidth={strokeWidth}',
    "        strokeDasharray={dashed ? '8 6' : `${length}`}",
    '        strokeDashoffset={dashed ? 0 : length * (1 - progress)}',
    '        strokeLinecap="round"',
    "        opacity={interpolate(progress, [0, 0.1], [0, 1], {extrapolateLeft:'clamp', extrapolateRight:'clamp'})}",
    '      />',
    '      {progress > 0.8 && (',
    '        <circle',
    '          cx={interpolate(progress, [0,1], [x1, x2])}',
    '          cy={interpolate(progress, [0,1], [y1, y2])}',
    '          r={4}',
    '          fill={color}',
    "          opacity={interpolate(progress, [0.8, 1], [0, 1], {extrapolateLeft:'clamp', extrapolateRight:'clamp'})}",
    '        />',
    '      )}',
    '    </svg>',
    '  );',
    '};',
  ].join('\n'),

  ProgressDots: [
    'const ProgressDots:React.FC<{',
    '  total:number;',
    '  current:number;',
    '  d:number;',
    '  accent?:string;',
    "  position?:'bottom'|'right';",
    "}> = ({total, current, d, accent=C.accent, position='bottom'}) => {",
    '  const frame = useCurrentFrame();',
    "  const isHorizontal = position === 'bottom';",
    '  ',
    '  return (',
    '    <E d={d} from="pop" style={{',
    "      position: 'absolute',",
    '      ...(isHorizontal ',
    "        ? {bottom: 60, left: '50%', transform: 'translateX(-50%)'}",
    "        : {right: 80, top: '50%', transform: 'translateY(-50%)'}",
    '      ),',
    '    }}>',
    '      <div style={{',
    "        display: 'flex',",
    "        flexDirection: isHorizontal ? 'row' : 'column',",
    '        gap: 12,',
    "        alignItems: 'center',",
    '      }}>',
    '        {Array.from({length: total}).map((_, i) => {',
    '          const isActive = i === current;',
    '          const isPast = i < current;',
    '          return (',
    '            <div key={i} style={{',
    '              width: isActive ? (isHorizontal ? 32 : 8) : 8,',
    '              height: isActive ? (isHorizontal ? 8 : 32) : 8,',
    '              borderRadius: 4,',
    "              backgroundColor: isActive ? accent : isPast ? `${accent}60` : 'rgba(255,255,255,0.15)',",
    "              transition: 'none',",
    '            }}/>',
    '          );',
    '        })}',
    '      </div>',
    '    </E>',
    '  );',
    '};',
  ].join('\n'),

  AccentSeparator: [
    'const AccentSeparator:React.FC<{',
    '  d:number;',
    '  width?:number;',
    '  color?:string;',
    "  variant?:'line'|'dots'|'gradient';",
    "}> = ({d, width=80, color=C.accent, variant='line'}) => {",
    '  const frame = useCurrentFrame();',
    '  const progress = interpolate(frame - d, [0, 25], [0, 1], {',
    '    easing: Easing.bezier(0.16, 1, 0.3, 1),',
    "    extrapolateLeft: 'clamp', extrapolateRight: 'clamp',",
    '  });',
    '  ',
    "  if (variant === 'dots') {",
    '    return (',
    "      <div style={{display:'flex', gap:8, justifyContent:'center', opacity: progress}}>",
    '        {[0,1,2].map(i => (',
    '          <div key={i} style={{',
    '            width: 6, height: 6, borderRadius: 3,',
    '            backgroundColor: i === 1 ? color : `${color}40`,',
    '            transform: `scale(${interpolate(',
    '              frame - d - i * 5, [0, 15], [0, 1],',
    "              {easing: Easing.bezier(0.34, 1.56, 0.64, 1), extrapolateLeft:'clamp', extrapolateRight:'clamp'}",
    '            )})`,',
    '          }}/>',
    '        ))}',
    '      </div>',
    '    );',
    '  }',
    '  ',
    "  if (variant === 'gradient') {",
    '    return (',
    '      <div style={{',
    "        width: width * progress, height: 2, margin: '0 auto',",
    '        background: `linear-gradient(90deg, transparent, ${color}, transparent)`,',
    '        borderRadius: 1,',
    '      }}/>',
    '    );',
    '  }',
    '  ',
    '  return (',
    '    <div style={{',
    '      width: width * progress, height: 2,',
    "      backgroundColor: color, borderRadius: 1, margin: '0 auto',",
    '    }}/>',
    '  );',
    '};',
  ].join('\n'),

  CascadeItem: [
    '// CascadeItem — stagger with blur (depth of field effect)',
    'const CascadeItem:React.FC<{d:number;index:number;children:React.ReactNode}> = ({d,index,children}) => {',
    '  const frame = useCurrentFrame();',
    '  const delay = d + index * 8;',
    '  const dist = 60 + index * 15;',
    '  const dur = 22 + index * 2;',
    '  const progress = interpolate(frame - delay, [0, dur], [0, 1], {',
    '    easing: Easing.bezier(0.16, 1, 0.3, 1),',
    "    extrapolateLeft: 'clamp', extrapolateRight: 'clamp',",
    '  });',
    '  return (',
    '    <div style={{',
    '      opacity: progress,',
    '      transform: `translateY(${interpolate(progress,[0,1],[dist,0])}px)`,',
    '      filter: `blur(${interpolate(progress,[0,0.5,1],[4,1,0])}px)`,',
    '    }}>{children}</div>',
    '  );',
    '};',
  ].join('\n'),

  OdometerDigit: [
    '// OdometerDigit — number that counts up digit by digit',
    'const OdometerDigit:React.FC<{value:number;d:number;fontSize?:number;color?:string}> = ({value,d,fontSize=96,color=C.accent}) => {',
    '  const frame = useCurrentFrame();',
    '  const progress = interpolate(frame - d, [0, 40], [0, 1], {',
    '    easing: Easing.bezier(0.16, 1, 0.3, 1),',
    "    extrapolateLeft: 'clamp', extrapolateRight: 'clamp',",
    '  });',
    '  const current = Math.round(interpolate(progress, [0,1], [0, value]));',
    "  const digits = String(current).split('');",
    '  return (',
    "    <div style={{display:'flex',overflow:'hidden',height:fontSize*1.2}}>",
    '      {digits.map((digit, i) => {',
    '        const dp = interpolate(frame - d - i*3, [0,30], [0,1], {',
    "          easing: Easing.bezier(0.16,1,0.3,1), extrapolateLeft:'clamp', extrapolateRight:'clamp',",
    '        });',
    "        return <div key={i} style={{fontSize,fontWeight:700,color,fontFamily:\"'DM Sans',sans-serif\",lineHeight:1.2,opacity:dp,",
    '          transform:`translateY(${interpolate(dp,[0,1],[fontSize*0.5,0])}px)`}}>{digit}</div>;',
    '      })}',
    '    </div>',
    '  );',
    '};',
  ].join('\n'),

  AnimatedMetric: [
    '// AnimatedMetric — number + suffix + label',
    "const AnimatedMetric:React.FC<{value:number;suffix:string;label:string;d:number;accent?:string}> = ({value,suffix,label,d,accent=C.accent}) => (",
    "  <div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:12}}>",
    "    <div style={{display:'flex',alignItems:'baseline',gap:4}}>",
    '      <OdometerDigit value={value} d={d} fontSize={96} color={accent}/>',
    '      <E d={d+15} from="pop"><span style={{fontSize:48,fontWeight:700,color:accent}}>{suffix}</span></E>',
    '    </div>',
    "    <E d={d+20} from=\"up\"><span style={{fontSize:22,fontWeight:400,color:C.dim,textTransform:'uppercase',letterSpacing:3}}>{label}</span></E>",
    '  </div>',
    ');',
  ].join('\n'),

  MorphPosition: [
    '// MorphPosition — element that smoothly repositions between phases',
    'const MorphPosition:React.FC<{children:React.ReactNode;phase:number;fromY:number;toY:number;fromX?:number;toX?:number;fromScale?:number;toScale?:number;d:number;duration?:number}> = ',
    '  ({children,phase,fromY,toY,fromX=0,toX=0,fromScale=1,toScale=1,d,duration=25}) => {',
    '  const frame = useCurrentFrame();',
    '  const mp = interpolate(frame - d, [0, duration], [0, phase], {',
    '    easing: Easing.bezier(0.45, 0, 0.55, 1),',
    "    extrapolateLeft: 'clamp', extrapolateRight: 'clamp',",
    '  });',
    '  return (',
    "    <div style={{transform:`translate(${interpolate(mp,[0,1],[fromX,toX])}px,${interpolate(mp,[0,1],[fromY,toY])}px) scale(${interpolate(mp,[0,1],[fromScale,toScale])})`,transformOrigin:'center center'}}>",
    '      {children}',
    '    </div>',
    '  );',
    '};',
  ].join('\n'),
};

// ──────────────────────────────────────────────────────────────────────────────
// Type → component mapping (only advanced components; E, Fd, Safe, C always included)
// ──────────────────────────────────────────────────────────────────────────────

const TYPE_COMPONENTS = {
  title:       ['AnimatedText', 'AccentSeparator'],
  callout:     ['AnimatedText', 'AccentSeparator'],
  reveal:      ['AnimatedText', 'MorphPosition'],
  icons:       ['CascadeItem'],
  cards:       ['GlowCard', 'AnimatedLine'],
  diagram:     ['GlowCard', 'AnimatedLine'],
  steps:       ['GlowCard', 'ProgressDots'],
  chart:       ['AccentSeparator'],
  metrics:     ['GlowCard', 'OdometerDigit', 'AnimatedMetric', 'AccentSeparator'],
  gauge:       ['OdometerDigit', 'AnimatedMetric'],
  list:        ['CascadeItem', 'AccentSeparator'],
  comparison:  ['GlowCard'],
  beforeafter: ['GlowCard'],
  funnel:      ['GlowCard', 'ProgressDots'],
  timeline:    ['AnimatedLine', 'ProgressDots'],
  ui:          ['GlowCard'],
};

function _getComponentsForType(type) {
  const needed = TYPE_COMPONENTS[type] || [];
  // Deduplicate and resolve dependencies (AnimatedMetric needs OdometerDigit)
  const set = new Set(needed);
  if (set.has('AnimatedMetric') && !set.has('OdometerDigit')) set.add('OdometerDigit');
  // Build in definition order to respect dependencies
  const order = ['AnimatedText', 'GlowCard', 'AnimatedLine', 'ProgressDots', 'AccentSeparator', 'CascadeItem', 'OdometerDigit', 'AnimatedMetric', 'MorphPosition'];
  return order.filter(name => set.has(name)).map(name => COMP_DEFS[name]).join('\n\n');
}

module.exports = { getComponentsForType: _getComponentsForType };
